# Generated by Django 4.0.3 on 2022-03-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_chocie_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chocie_text',
            new_name='choice_text',
        ),
    ]
